#pragma config(Sensor, S1,     floorSensor,    sensorEV3_Color)
#pragma config(Sensor, S2,     bumpSensor,     sensorEV3_Touch)
#pragma config(Sensor, S3,     lightSensor,    sensorLightInactive)
#pragma config(Sensor, S4,     colorSensor,    sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Motor,  motorA,           ,             tmotorEV3_Medium, openLoop)
#pragma config(Motor,  motorB,          left_motor,    tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          cage,          tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorD,          right_motor,   tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define TIMEOUT 20

/******************** PROTOTYPES ********************/
void toss_egg();
void detect_nest();
void drive_to_nest();
void rotate_180();
void rotate_70();
int scan_egg();
void capture_egg();
void backup(int reverse);
void escape_nest();

/******************** TASK MAIN ********************/
task main()
{
	int go = 1;
  int allColours;
  int touchStatus = 0;
  int elapsedTime = 0;

  //reset timer
  resetTimer(T1);

	while (go == 1)
	{

		//drive forward looking for eggs
	  setMotor(left_motor, 50);
    setMotor(right_motor, 50);
    wait1Msec(50);

    //activate sensors and timer in loop
    elapsedTime = getTimer(T1,seconds);
    allColours = scan_egg();
    touchStatus = getTouchValue(bumpSensor);

    //if hit a wall
	  if (touchStatus == 1)
	  {
	  	//if in nest
	  	if (getColorReflected(floorSensor) > 50)
	  	{
	  		backup(0);
	  		backup(0);
	  		rotate_70();
	  		stopAllMotors();
	  	}
	  	else
	  	{
	  		backup(0);
	  		rotate_70();
	  		stopAllMotors();
	  	}//end if in nest
	  	resetTimer(T1);
	  }//end if hits wall

	  //if egg detected
	  if (allColours > 1)
	  {
	  	//correct for mistaking nest light for egg
	  	if (getColorReflected(floorSensor) > 50)
	  	{
	  		escape_nest();
	  		resetTimer(T1);
	  	}
	  	else
	  	{
	  		capture_egg();
				allColours = scan_egg();

				//if black egg detected
	  		if (allColours > 1 && allColours < 9)
	  		{
	  			writeDebugStreamLine("Colour detected: Black");
	  			detect_nest();
	  			rotate_180();
	  			toss_egg();
	  			rotate_70();
	    	}
	    	//if pastel egg detected
	  		else if (allColours >= 9)
	  		{
	  			writeDebugStreamLine("Colour detected: Pastel");
	  			detect_nest();
	  			rotate_180();
	  			drive_to_nest();
	  			//reverse backup
	  			backup(1);
	  			rotate_180();
	  			toss_egg();
	  			backup(0);
	  			rotate_180();
	  		}
	  		//if no egg in chamber (egg not captured)
	  		else
	  		{
	  			writeDebugStreamLine("No egg in cage");
	  			setMotorTarget(cage, 0, 100);
					waitUntilMotorStop(cage);
					wait1Msec(100);
					stopAllMotors();
	  		}//end coloured egg detection
	  	}//end correct for false nest light issue
	  	resetTimer(T1);
	  }//end egg detection

	  //timer failsafe if robot gets stuck
	  if (elapsedTime > TIMEOUT)
	  {
	  	backup(0);
	  	rotate_70();
	  	resetTimer(T1);
	  }

	}//end while
}//end task main

/******************** DETECT NEST ********************/
void detect_nest()
{
  int largestLightSeen=0;

  //scan for nest light
  resetMotorEncoder(left_motor);
  resetMotorEncoder(right_motor);
  while (getMotorEncoder(right_motor) < 830)
  {
  	moveMotorTarget(left_motor, -2000, -20);
    moveMotorTarget(right_motor, 2000, 15);

    if(SensorValue[lightSensor]>largestLightSeen)
   {
 		largestLightSeen = SensorValue[lightSensor];
   }
   wait1Msec(50);
  }

  //failsafe if no light detected
  if (largestLightSeen < 5)
  {
  	backup(0);
  	detect_nest();
  }

  //turn to the light
  setMotor(left_motor, 20);
  setMotor(right_motor, -15);
  while(SensorValue[lightSensor] < (largestLightSeen - 2))
  {
  	wait1Msec(50);
  }
  stopAllMotors();
}

/******************** DRIVE TO NEST ********************/
void drive_to_nest()
{
	int nest = 0;
	int touchStatus = 0;

	while (nest < 50)
	{
		nest = getColorReflected(floorSensor);
		setMotor(left_motor, -100);
    setMotor(right_motor, -83); //80 curves left, 85 right, 82 left,
    wait1Msec(50);

    //failsafe if hits a wall or robot on the way
    touchStatus = getTouchValue(bumpSensor);
    if (touchStatus == 1)
    {
    	backup(1);
    	detect_nest();
    	rotate_180();
	  	drive_to_nest();
    }
	}
}

/******************** ROTATE 180 ********************/
void rotate_180()
{
	setMotor(left_motor, -100);
  setMotor(right_motor, 83);
  wait1Msec(630); /*650 acceptable, */
  stopAllMotors();
}

/******************** ROTATE 70 ********************/
void rotate_70()
{
	setMotor(left_motor, -100);
  setMotor(right_motor, 83);
  wait1Msec(550);
  stopAllMotors();
}

/******************** CAPTURE EGG ********************/
void capture_egg()
{
	setMotorTarget(cage, -100 , 100);
	waitUntilMotorStop(cage);
	sleep(200);
}

/******************** SCAN EGG ********************/
int scan_egg()
{
	long redValue;
	long greenValue;
  long blueValue;
  int allColours;

  getColorRGB(colorSensor, redValue, greenValue, blueValue);
	allColours = redValue + greenValue + blueValue;
	return allColours;
}

/******************** TOSS EGG ********************/
void toss_egg()
{
	setMotorTarget(cage, 0, 100);
	waitUntilMotorStop(cage);
	sleep(300);
	setMotor(left_motor, 100);
  setMotor(right_motor, 83);
  wait1Msec(1000);
  stopAllMotors();
}

/******************** BACKUP ********************/
void backup(int reverse)
{
	if (reverse == 1)
	{
		setMotor(left_motor, 100);
    setMotor(right_motor, 83);
    wait1Msec(800);
	}
	else
	{
		setMotor(left_motor, -100);
    setMotor(right_motor, -83);
    wait1Msec(800);
	}
}

/******************** ESCAPE NEST ********************/
void escape_nest()
{
	int touchStatus = 0;
	int elapsedTime = 0;

	//timer for while loop below
	resetTimer(T2);

	while (getColorReflected(floorSensor) > 50)
	{
		//keep T1 from interfering
		resetTimer(T1);

		//set T2 to record time in while loop
		elapsedTime = getTimer(T2,seconds);

		//drive forward
		setMotor(left_motor, 50);
    setMotor(right_motor, 50);
    wait1Msec(50);

		//if hit wall
		touchStatus = getTouchValue(bumpSensor);
		if (touchStatus == 1)
		{
			backup(0);
			rotate_70();
			resetTimer(T2);
		}

		if (elapsedTime > 4)
		{
			rotate_70();
			resetTimer(T2);
		}

	}//end while

	//reset timer
}
